services:
  laravel:
    build:
      context: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      - .:/workspace:cached
    working_dir: /workspace
