services:
  _defaults:
    autowire: true

  FizzBuzz\:
    resource: '../src/*'

  FizzBuzz\App\FizzBuzzSequencePrinter:
    public: true

  FizzBuzz\Core\NumberConverter:
    arguments:
      $rules:
        - '@fizzbuzz.rule.fizz'
        - '@fizzbuzz.rule.buzz'
        - '@FizzBuzz\Spec\PassThroughRule'

  fizzbuzz.rule.fizz:
    class: FizzBuzz\Spec\CyclicNumberRule
    arguments: [3, 'Fizz']

  fizzbuzz.rule.buzz:
    class: FizzBuzz\Spec\CyclicNumberRule
    arguments: [5, 'Buzz']